### ISSUE TITLE
Web demo test is Passed in Jenkins but contains errors in Log

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#315] opened 2020-10-06 15:32 UTC
Steps:
1. Install zebrunner ce
2. Run Register repository via Jenkins
3. Run Web demo test
Actual result: Test run is not appeared in Reporting
Web demo test is Passed in Jenkins but contains errors in Log

**Comment by vdelendik** [comment] 2020-10-29 20:25
closing as can't reproduce. need more details or logs to prove

**Closed by vdelendik** 2020-10-29 20:25 UTC
Labels: bug, invalid
