### ISSUE TITLE
Delete button UI is broken after clicking Delete then cancel on confirmation modal

### ISSUE THREAD

**Issue by kdaroshka** [zebrunner/zebrunner#2119] opened 2020-04-16 17:28 UTC
Zebranner: ui v.1.1.0 | server v.1.1.1
Chrome: version 80.0.3987.163 (Official Build) (64-bit)

Steps:
1. Open Runs page
2. Select 1 or more runs by checking check boxes 
3. Click Delete button
4. Click Cancel on confirmation window
Actual result: Confirmation window is dismissed. Delete button UI is broken
Expected result: Confirmation window is dismissed. Delete button UI doesn't change

Note: bug is resolved by refreshing the page / clicking around the page

![Screenshot 2020-04-16 20 07 22](https://user-images.githubusercontent.com/24683436/79487450-ec4d0200-8020-11ea-825b-1f25d3cbd1f0.png)

**Comment by lmikhadyuk** [comment] 2020-04-16 17:33
Duplicate of https://github.com/zebrunner/zebrunner/issues/2115.

**Closed by lmikhadyuk** 2020-04-16 17:33 UTC
