### ISSUE TITLE
After Upgrade zebrunner ce 1.3->1.4 User can't sign in to reporting 

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#385] opened 2021-01-21 16:31 UTC
Steps:
1. git clone --recurse-submodule --branch 1.3 https://github.com/zebrunner/zebrunner.git
2. git checkout master
3. ./zebrunner.sh setup
4. git checkout develop
5. git pull --recurse-submodules
6. ./zebrunner.sh upgrade
7. Start Jenking
8. Start Reporting
Actual result: user can't sign in to reporting, 500 error

Log:
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'widgetService' defined in URL [jar:file:/app/reporting-service.jar!/BOOT-INF/classes!/com/zebrunner/reporting/service/WidgetService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freemarkerUtil': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'TEMPLATES_DIRECTORY' in value "${TEMPLATES_DIRECTORY}"
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freemarkerUtil': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'TEMPLATES_DIRECTORY' in value "${TEMPLATES_DIRECTORY}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAut

**Comment by vdelendik** [comment] 2021-01-22 11:45
closing as can't reproduce. there is amistake in test scenarion.
we have to clone originally from master and setup 1.3 using master codebase without 1.3 tag and extra checkout.
```
git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
```
Clarification: 1.3 tag was registered to test 1.2->1.3 upgrade and not correlate with final 1.3 release:( In 1.4 I'll try to fix it and have tag and release in sync

**Closed by vdelendik** 2021-01-22 11:45 UTC
Labels: bug, invalid

**Comment by vdelendik** [comment] 2021-01-25 14:31
verified on prod
