### ISSUE TITLE
Docker network does not exist

### ISSUE THREAD

**Issue by brutskov** [zebrunner/zebrunner#2139] opened 2020-05-08 15:10 UTC
'infra' network does not created on docker compose start

**Comment by vdelendik** [comment] 2020-05-11 10:51
fixed: https://github.com/zebrunner/zebrunner/pull/2140

**Comment by nsidorevich** [comment] 2020-05-20 18:18
@brutskov please config that the issue is resolved and feel free to close this one

**Closed by nsidorevich** 2020-05-20 18:18 UTC
Labels: status: pending-review, status: ready-for-qa, type: bug
