### ISSUE TITLE
Selenium Grid Hub v. not found after running Jenkins

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#401] opened 2021-01-29 17:00 UTC
**Test scenario:**

**Pre conditions:**
Demo.zebrunner.farm running without jenkins

1../zebrunner.sh stop
2../zebrunner.sh setup
3.Tap Jenkins enable Y
4.Open https://........./jenkins
5.Enter login/password

**Actual result:**  Selenium Grid Hub v. not found after running Jenkins

<img width="1283" alt="Screenshot 2021-01-29 at 19 55 58" src="https://user-images.githubusercontent.com/50950954/106304129-06806580-626c-11eb-995a-6ed7253a7389.png">
`

`Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-01-29 15:20:48.148+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @464ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-01-29 15:20:48.214+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2021-01-29 15:20:48.296+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 11.0.9+11
2021-01-29 15:20:48.581+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /jenkins, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-01-29 15:20:48.655+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2021-01-29 15:20:48.655+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2021-01-29 15:20:48.657+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2021-01-29 15:20:49.081+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-01-29 15:20:49.194+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@6f95cd51{Jenkins v2.267,/jenkins,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2021-01-29 15:20:49.221+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@7a8c8dcf{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2021-01-29 15:20:49.221+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @1538ms
2021-01-29 15:20:49.225+0000 [id=25]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2021-01-29 15:20:49.458+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2021-01-29 15:20:49.726+0000 [id=42]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jenkins.ClassLoaderReflectionToolkit (file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.267.jar) to method java.lang.ClassLoader.findClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of jenkins.ClassLoaderReflectionToolkit
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-01-29 15:20:55.346+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2021-01-29 15:20:55.352+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2021-01-29 15:20:56.944+0000 [id=35]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2021-01-29 15:20:56.944+0000 [id=35]	INFO	j.a.PrioritySorterPlugin#init1: Configuring the Priority Sorter ...
2021-01-29 15:20:56.985+0000 [id=43]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2021-01-29 15:20:56.986+0000 [id=38]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2021-01-29 15:20:57.053+0000 [id=35]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2021-01-29 15:20:57.053+0000 [id=35]	INFO	j.a.PrioritySorterPlugin#init2: Sorting existing Queue ...
2021-01-29 15:20:57.055+0000 [id=41]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2021-01-29 15:20:57.060+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/configGradleAutoInstaller.groovy
2021-01-29 15:20:57.069+0000 [id=35]	INFO	j.a.sorter.AdvancedQueueSorter#init: Initialized the QueueSorter with 0 Buildable Items
2021-01-29 15:20:57.096+0000 [id=66]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Download metadata
2021-01-29 15:20:57.101+0000 [id=66]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Download metadata. 4 ms
2021-01-29 15:20:57.536+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/configMavenAutoInstaller.groovy
2021-01-29 15:20:57.673+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/configSbtAutoInstaller.groovy
2021-01-29 15:20:57.817+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/configScriptApproval.groovy
2021-01-29 15:20:57.908+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/disable-scripts-security-for-job-dsl-scripts.groovy
--> disabling scripts security for job dsl scripts
2021-01-29 15:20:57.992+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/global-args-security.groovy
Zebrunner Jenkins global initialization already happened.
Put Zebrunner Pipeline URL: https://github.com/zebrunner/pipeline-ce.git
Put Zebrunner Pipeline version: 1.4
2021-01-29 15:20:58.831+0000 [id=41]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
2021-01-29 15:20:58.860+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2021-01-29 15:20:58.936+0000 [id=24]	WARNING	j.branch.WorkspaceLocatorImpl#getWorkspaceRoot: JENKINS-2111 path sanitization ineffective when using legacy Workspace Root Directory ‘${ITEM_ROOTDIR}/workspace’; switch to ‘${JENKINS_HOME}/workspace/${ITEM_FULL_NAME}’ as in JENKINS-8446 / JENKINS-21942
2021-01-29 15:20:58.942+0000 [id=24]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
2021-01-29 15:21:00.029+0000 [id=81]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Connection #1 failed: java.io.EOFException
2021-01-29 15:21:00.052+0000 [id=82]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #2 from /172.18.0.22:48602
--> setting agent port for jnlp
--> setting agent port for jnlp... done
2021-01-29 15:28:13.391+0000 [id=123]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Periodic background build discarder
2021-01-29 15:28:13.408+0000 [id=123]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Periodic background build discarder. 16 ms

**Comment by vdelendik** [comment] 2021-02-09 21:14
closing as can't reproduce using latest develop branch.
also @dhreben you forgot to mention that reporting component must be disabled as well!

**Closed by vdelendik** 2021-02-09 21:14 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2021-02-15 09:03
Closed.  Can't reproduce using latest develop branch
