### ISSUE TITLE
Register repository works with errors in 1.1

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#343] opened 2020-11-04 11:16 UTC
Steps:
1. git clone --recurse-submodule https://github.com/zebrunner/zebrunner.git
2. cd zebrunner 
3. Run ./zebrunner.sh setup 
4. Register organization
5. Register Repository on branch: master, jdk8
Actual result: Register Repository is failed
Log1:
OnPush job
13:53:40  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project carina-demo: Fatal error compiling: invalid target release: 11 -> [Help 1]
13:53:40  [ERROR] 
13:53:40  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
13:53:40  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
13:53:40  [ERROR] 
13:53:40  [ERROR] For more information about the errors and possible solutions, please read the following articles:
13:53:40  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }

Log2:
15:57:32  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project carina-demo: No branches currently exist in this project. Please scan the main branch without passing any branch parameters. -> [Help 1]
15:57:32  [ERROR] 
15:57:32  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
15:57:32  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:57:32  [ERROR] 
15:57:32  [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:57:32  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }

**Comment by vdelendik** [comment] 2020-11-12 15:40
closing as not a bug. just a conflicts with java version in code and slave

**Closed by vdelendik** 2020-11-12 15:40 UTC
Labels: bug, wontfix
