### ISSUE TITLE
General board widgets have unused JOB_NAME filter enabled

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/zebrunner#1788] opened 2019-10-12 11:08 UTC
![image](https://user-images.githubusercontent.com/4551455/66700503-b76e9400-ecf9-11e9-8960-fba3417a0ef0.png)

**Comment by nsidorevich** [comment] 2019-11-14 12:47
Duplicates #1665, closing older one.
@vdelendik could you please add desired behavior?

**Comment by vdelendik** [comment] 2019-11-14 13:03
JOB_NAME as enabled parameter appeared due to the inconsistency with params and labels...
By default after installing fresh system it should be disabled and located among "SHOW MORE" filters

**Comment by lmikhadyuk** [comment] 2020-03-18 13:49
Unable to reproduce in ui: 1.405-SNAPSHOT server: 1.593-SNAPSHOT client: 1.0-SNAPSHOT.

**Closed by lmikhadyuk** 2020-03-18 13:49 UTC
Labels: type: bug
