### ISSUE TITLE
"Bad message 431" is in logs of jobs

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#426] opened 2021-03-01 12:19 UTC
Steps:
1. Clone zebrunner from develop branch
2. Set up zebrunner(minio)
3. Register organization qaprosoft
4. Register repo
5. Start API, Web demo job
6. Actual result: "Bad message 431" is in logs of jobs
Note: when job is completed all log is visible without Bad message

**Comment by vdelendik** [comment] 2021-03-02 22:57
closing as can't reproduce on latest env from develop

**Closed by vdelendik** 2021-03-02 22:57 UTC
Labels: bug, invalid

**Comment by okamara** [comment] 2021-03-03 14:12
Can't repro after cleaning cookies
