### ISSUE TITLE
After disabled reporting we have not question about AWS S3 storage,SMTP and Github

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#408] opened 2021-02-11 16:15 UTC

**Comment by vdelendik** [comment] 2021-02-12 09:40
closed as dupe of [#407] :)

**Closed by vdelendik** 2021-02-12 09:40 UTC
Labels: duplicate, enhancement

**Comment by dhreben** [comment] 2021-02-12 09:42
Closed as dupe of https://github.com/zebrunner/zebrunner/issues/407
