### ISSUE TITLE
 nginx/conf.d/default.conf returned to default values after setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/zebrunner#402] opened 2021-01-29 17:29 UTC
**Test scenario:**

1. ./zebrunner.sh setup 
2. Setup only mcloud 
2. Update nano nginx/conf.d/ default.conf 
3. ./zebrunner.sh stop
4. ./zebrunner.sh setup
5. Tap Jenkins enable Y
6. Open  nginx/conf.d/default.conf

**Actual result:**  nginx/conf.d/default.conf returned to default values after setup

**Comment by vdelendik** [comment] 2021-02-09 21:15
closing as a dupe of #401

**Closed by vdelendik** 2021-02-09 21:15 UTC
Labels: bug

**Comment by okamara** [comment] 2021-02-15 15:17
Close as dupe
