### ISSUE TITLE
Web demo test contains error message in log

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#427] opened 2021-03-01 12:56 UTC
Steps:
1. Clone zebrunner ce from develop branch
2. Register  organization qaprosoft
3. Register repository
4. Run Web demo test
5. Restart jenkins
5. Actual result: 
Web demo test contains error message in log -> java.lang.IllegalStateException: JENKINS-50407: no loaded shell in CpsFlowExecution[Owner[qaprosoft/carina-demo/Web-Demo-Test/1:qaprosoft/carina-demo/Web-Demo-Test #1]]
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by vdelendik** [comment] 2021-03-02 22:50
closing as can't reproduce on  mine env

**Closed by vdelendik** 2021-03-02 22:50 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2021-03-03 14:45
Can't reproduce.Closed
